# Generated by Django 5.1.2 on 2024-11-02 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_catrgory_product_vendor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='catrgory',
            new_name='category',
        ),
    ]
