# Generated by Django 5.1.2 on 2024-11-04 16:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_customer_address_line1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
