# Generated by Django 5.1.2 on 2024-11-04 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_customeraddress_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customeraddress',
            old_name='Customer',
            new_name='customer',
        ),
    ]
