# Generated by Django 5.1.2 on 2024-11-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_customer_customeraddress_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='primaryAddress',
            field=models.BooleanField(default=False),
        ),
    ]
