# Generated by Django 5.1.2 on 2024-11-05 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_productrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productrating',
            old_name='content',
            new_name='review',
        ),
    ]
