# Generated by Django 5.1.2 on 2024-11-05 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_content_productrating_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productrating',
            old_name='Customer',
            new_name='customer',
        ),
    ]
