# Generated by Django 5.1.4 on 2024-12-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_id',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
