# Generated by Django 5.1.4 on 2024-12-14 01:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_customeraddress_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='demoLink',
        ),
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.CharField(default=django.utils.timezone.now, editable=False, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
