# Generated by Django 5.1.4 on 2024-12-14 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_remove_product_demolink_product_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_id',
            new_name='item_id',
        ),
    ]
