# Generated by Django 5.1.4 on 2024-12-14 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_rename_product_id_product_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('discontinued', 'Discontinued')], default='Inactive', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
